-- =====================================================================================
-- CREDIFY - DATABASE SCHEMA (Day 2)
--
-- Run this whole file ONCE in the Supabase SQL Editor:
--   Supabase dashboard -> SQL Editor -> New query -> paste -> Run
--
-- It is safe to re-run: every statement uses IF NOT EXISTS or CREATE OR REPLACE.
--
-- One table. The MVP stores loan applications and nothing else, so it gets one table with
-- typed columns. Deliberately NOT done here:
--   * no `users` table        - there is no login yet (Day 1 decision)
--   * no `documents` table    - no uploads in the MVP
--   * no `scores` table       - the Day 3 scoring engine adds its own columns when it exists
--   * no JSONB blob of answers - see the note on column choice below
-- =====================================================================================

create table if not exists public.applications (
  -- ---------------------------------------------------------------------------------
  -- Identity
  -- ---------------------------------------------------------------------------------
  id                       uuid primary key default gen_random_uuid(),

  -- The short code the applicant quotes, e.g. CR-2026-7K4QP2. Generated by the app
  -- (src/lib/applications/reference.ts); UNIQUE here is what actually guarantees it.
  -- Readable, and therefore guessable: it identifies an application, it does not open one.
  reference                text        not null unique,

  -- The secret in the status-page URL: /status/<access_token>. Generated by Postgres so a
  -- bug in the app can never produce a predictable one. Because there is no login, this
  -- token IS the access control for the status page, which is why the status page exposes
  -- only a status and an analyst note, never financial figures.
  access_token             uuid        not null unique default gen_random_uuid(),

  -- ---------------------------------------------------------------------------------
  -- Workflow
  -- ---------------------------------------------------------------------------------
  -- A text column with a CHECK rather than a Postgres ENUM type. Adding a status to an
  -- ENUM needs ALTER TYPE and cannot be done inside a transaction with other changes;
  -- changing a CHECK is one ordinary statement. The five values mirror
  -- src/lib/applications/status.ts exactly.
  status                   text        not null default 'submitted'
                             check (status in ('submitted', 'in_review', 'information_requested',
                                               'approved', 'declined')),

  -- The one free-text message an analyst can send the applicant. Shown on the public
  -- status page, so it is written for the borrower, not for the credit file.
  analyst_message          text,

  submitted_at             timestamptz not null default now(),
  updated_at               timestamptz not null default now(),

  -- ---------------------------------------------------------------------------------
  -- Step 1: company information
  -- ---------------------------------------------------------------------------------
  company_name             text        not null,
  legal_form               text        not null,
  registration_number      text,
  industry                 text        not null,
  country                  text        not null,
  year_founded             integer     not null,
  employees                integer     not null,
  contact_name             text        not null,
  contact_email            text        not null,
  contact_phone            text,

  -- ---------------------------------------------------------------------------------
  -- Step 2: loan request
  -- ---------------------------------------------------------------------------------
  loan_amount_eur          numeric(14,2) not null check (loan_amount_eur > 0),
  loan_term_months         integer       not null check (loan_term_months > 0),
  loan_purpose             text          not null,
  purpose_description      text          not null,

  -- ---------------------------------------------------------------------------------
  -- Step 3: financial information
  --
  -- WHY SEPARATE COLUMNS AND NOT ONE JSONB BLOB?
  -- These nine figures are the inputs to the Day 3 scorecard and the columns the Day 4
  -- analyst dashboard sorts and filters by. As real columns they get types, CHECK
  -- constraints and indexes, and a typo in a key name fails loudly instead of returning
  -- NULL. A blob would be quicker to write today and worse every day after.
  --
  -- numeric(14,2), not float: money must not carry binary rounding error.
  -- EBITDA and net income allow negatives - a loss-making year is data, not an error.
  -- ---------------------------------------------------------------------------------
  fiscal_year              integer       not null,
  revenue_eur              numeric(14,2) not null check (revenue_eur >= 0),
  revenue_prior_year_eur   numeric(14,2) not null check (revenue_prior_year_eur >= 0),
  ebitda_eur               numeric(14,2) not null,
  net_income_eur           numeric(14,2) not null,
  interest_expense_eur     numeric(14,2) not null check (interest_expense_eur >= 0),
  existing_debt_eur        numeric(14,2) not null check (existing_debt_eur >= 0),
  total_assets_eur         numeric(14,2) not null check (total_assets_eur >= 0),
  current_assets_eur       numeric(14,2) not null check (current_assets_eur >= 0),
  current_liabilities_eur  numeric(14,2) not null check (current_liabilities_eur >= 0),

  -- Total liabilities and equity are REPORTED, not derived.
  --
  -- An earlier version of the engine worked equity out as
  --   total assets − interest-bearing debt − current liabilities
  -- which is unreliable in both directions: interest-bearing debt can overlap with current
  -- liabilities (the current portion of a term loan sits in both), and current liabilities
  -- miss long-term non-debt items such as provisions, deferred tax and lease obligations.
  -- The error goes the wrong way for a lender - it OVERSTATES equity, so the negative-equity
  -- critical flag fires less often than it should. Both figures are now asked for directly.
  --
  -- Nullable, because these columns were added after the table already held rows. Every new
  -- submission supplies them: the application form makes both required. See
  -- supabase/migrations/001_add_liabilities_and_equity.sql.
  -- Equity has no CHECK: negative equity is a real state and the flag the engine looks for.
  total_liabilities_eur    numeric(14,2) check (total_liabilities_eur >= 0),
  equity_eur               numeric(14,2)
);

-- The analyst dashboard (Day 4) lists newest first and filters by status.
-- UNIQUE on reference and access_token already creates their indexes.
create index if not exists applications_submitted_at_idx on public.applications (submitted_at desc);
create index if not exists applications_status_idx       on public.applications (status);

-- -------------------------------------------------------------------------------------
-- updated_at maintenance
--
-- The status page tells the applicant when their status last changed, so updated_at has to
-- be right even when a status is changed by hand in the Supabase table editor (which is
-- how Day 2 is tested, before the analyst screens exist). A trigger is the only way to
-- guarantee that; application code cannot.
-- -------------------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists applications_set_updated_at on public.applications;
create trigger applications_set_updated_at
  before update on public.applications
  for each row execute function public.set_updated_at();

-- =====================================================================================
-- ROW LEVEL SECURITY
--
-- Switched ON with NO policies, which means: every role WITHOUT the BYPASSRLS attribute is
-- refused, for every row, for reads and writes alike - however generous its table grants
-- may be. That covers anon and authenticated, the roles behind a publishable key.
--
-- (Grants are the other half of the story and are handled in the next section. A role needs
-- to pass both gates.)
--
-- That is intentional and is the whole security model. Credify's SECRET API key
-- (sb_secret_..., the replacement for the legacy service_role key) carries Postgres's
-- BYPASSRLS attribute, and that key exists in exactly one place: the Credify server process
-- (see src/lib/supabase/server.ts, which is marked "server-only" so a build fails if it
-- ever reaches the browser). Every read is therefore a query written in this repository,
-- and each of those queries names its columns explicitly.
--
-- Concretely: if a publishable key leaks, or someone finds the project URL, they get
-- nothing. If a policy is ever added here, financial data becomes reachable from the
-- internet - so do not add one until there is real authentication to hang it on.
-- =====================================================================================
alter table public.applications enable row level security;

-- =====================================================================================
-- TABLE PRIVILEGES (GRANTs) - A SEPARATE LAYER FROM RLS
--
-- These are two different gates, and both must be passed:
--
--   GRANT  decides whether a role may touch the table AT ALL.
--   RLS    decides which ROWS a role may see, once it is past the grant.
--
-- A role with no grant is refused before RLS is ever consulted: PostgREST returns
-- `42501: permission denied for table applications`. So RLS being enabled says nothing
-- about who can reach this table - the grants below do.
--
-- WHY THIS SECTION EXISTS AT ALL
-- Supabase used to grant select/insert/update/delete on every new table in `public` to
-- anon, authenticated and service_role automatically. That behaviour is controlled by the
-- Data API setting "Automatically expose new tables", which is now OFF by default on new
-- projects. With it off, a table created by this file is reachable by NOBODY - including
-- Credify's own secret key - until it is granted explicitly.
--
-- Granting here rather than relying on that setting is the better arrangement anyway: the
-- permissions live in version control next to the table they describe, they are reviewable
-- in a diff, and a fresh project reproduces them exactly whatever the dashboard toggle says.
-- =====================================================================================

-- The one role Credify uses. `service_role` is what the secret key (sb_secret_...)
-- authenticates as.
--
-- SELECT, INSERT and UPDATE - and deliberately NOT DELETE. The application never deletes a
-- row: submissions are a record, and an analyst changes a status rather than removing a
-- case. Withholding DELETE means neither a bug in this codebase nor a leaked key can
-- destroy submitted credit applications. Add it only when something genuinely needs to.
--
-- No sequence grants are needed: the primary key is a uuid from gen_random_uuid(), not a
-- serial, so there is no sequence to use.
do $$
begin
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    grant usage on schema public to service_role;
    grant select, insert, update on public.applications to service_role;
  else
    -- Not an error: `service_role` is a Supabase role and is absent from a plain Postgres,
    -- where this file may be run to test the schema itself.
    raise notice 'Role "service_role" not found; skipping grants. Expected outside Supabase.';
  end if;
end;
$$;

-- The two public roles get nothing. `anon` backs the publishable key and `authenticated`
-- backs a logged-in user, and neither should reach this table: Credify's browser code never
-- talks to Supabase.
--
-- REVOKE rather than simply not granting, so that this holds even on a project where
-- "Automatically expose new tables" is still ON and has already granted them access. It is
-- also belt and braces for RLS: if someone later turns RLS off by accident, these revokes
-- still stand between a publishable key and every applicant's financial figures.
--
-- Wrapped in a check because these are Supabase's own roles and do not exist in a plain
-- Postgres. The Supabase SQL Editor runs this file as ONE transaction, so an error on the
-- last line would roll back the table as well - hence the guard rather than a bare REVOKE.
do $$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on public.applications from anon;
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    revoke all on public.applications from authenticated;
  end if;
end;
$$;
