import "server-only";
import { getSupabaseAdmin } from "@/lib/supabase/server";
import { generateReference } from "./reference";
import { DEFAULT_STATUS, isApplicationStatus, type ApplicationStatus } from "./status";
import type { ApplicationInput } from "./schema";

/**
 * REPOSITORY: the only file in the app that knows the shape of the `applications` table.
 *
 * Everything else works with the typed objects below. If a column is renamed, this file
 * changes and nothing else does. It also means the two public pages cannot accidentally
 * read a column they should not: each query lists its columns explicitly, and the applicant
 * views do not name a single financial one.
 *
 * Column names are snake_case because that is Postgres convention; the app uses camelCase.
 * The mapping happens here, once.
 */

const TABLE = "applications";

/** What the caller gets back after a successful submission. */
export interface SubmittedApplication {
  reference: string;
  accessToken: string;
}

/**
 * What the CONFIRMATION page may show: the applicant is looking at this seconds after
 * typing it, on their own device.
 */
export interface ConfirmationView {
  reference: string;
  companyName: string;
  submittedAt: string;
}

/**
 * What the PUBLIC STATUS page may show, and the reason this type is narrow.
 *
 * The status page is reached by a link with a random token and no password. Anyone holding
 * that link, including anyone it was forwarded to, sees exactly these four values. So the
 * borrower's financial figures, the contact details and (from Day 3) the score and risk
 * grade are not in this type, are not in the SELECT that fills it, and therefore never
 * leave the database. Privacy is enforced by the query, not by remembering not to render
 * something.
 */
export interface ApplicantStatusView {
  reference: string;
  status: ApplicationStatus;
  analystMessage: string | null;
  statusUpdatedAt: string;
}

/** Postgres error code for a UNIQUE constraint violation. */
const UNIQUE_VIOLATION = "23505";

/**
 * Stores a validated application and returns its reference and status-page token.
 *
 * The reference is generated in the app, so two submissions arriving in the same
 * millisecond could in principle draw the same code. The database's UNIQUE constraint
 * catches that, and we simply try again with a new code. Three attempts is plenty: with a
 * 729-million-wide code space, a second collision is not a scenario worth engineering for.
 */
export async function insertApplication(input: ApplicationInput): Promise<SubmittedApplication> {
  const supabase = getSupabaseAdmin();

  for (let attempt = 1; attempt <= 3; attempt += 1) {
    const reference = generateReference();

    const { data, error } = await supabase
      .from(TABLE)
      .insert({
        reference,
        status: DEFAULT_STATUS,

        // Step 1: company information
        company_name: input.companyName,
        legal_form: input.legalForm,
        registration_number: input.registrationNumber,
        industry: input.industry,
        country: input.country,
        year_founded: input.yearFounded,
        employees: input.employees,
        contact_name: input.contactName,
        contact_email: input.contactEmail,
        contact_phone: input.contactPhone,

        // Step 2: loan request
        loan_amount_eur: input.loanAmountEur,
        loan_term_months: input.loanTermMonths,
        loan_purpose: input.loanPurpose,
        purpose_description: input.purposeDescription,

        // Step 3: financial information
        fiscal_year: input.fiscalYear,
        revenue_eur: input.revenueEur,
        revenue_prior_year_eur: input.revenuePriorYearEur,
        ebitda_eur: input.ebitdaEur,
        net_income_eur: input.netIncomeEur,
        interest_expense_eur: input.interestExpenseEur,
        existing_debt_eur: input.existingDebtEur,
        total_assets_eur: input.totalAssetsEur,
        current_assets_eur: input.currentAssetsEur,
        cash_eur: input.cashEur,
        current_liabilities_eur: input.currentLiabilitiesEur,
        total_liabilities_eur: input.totalLiabilitiesEur,
        equity_eur: input.equityEur,
      })
      // access_token is generated by Postgres (gen_random_uuid), so we read it back
      // rather than inventing it here.
      .select("reference, access_token")
      .single();

    if (!error) {
      return { reference: data.reference as string, accessToken: data.access_token as string };
    }

    const isReferenceCollision = error.code === UNIQUE_VIOLATION && error.message.includes("reference");
    if (!isReferenceCollision || attempt === 3) {
      throw new Error(`Could not save the application: ${error.message}`);
    }
  }

  // Unreachable: the loop either returns or throws.
  throw new Error("Could not save the application.");
}

/** Reads the confirmation page's data. Returns null when the token matches nothing. */
export async function getConfirmation(accessToken: string): Promise<ConfirmationView | null> {
  const supabase = getSupabaseAdmin();

  const { data, error } = await supabase
    .from(TABLE)
    .select("reference, company_name, submitted_at")
    .eq("access_token", accessToken)
    .maybeSingle();

  if (error) throw new Error(`Could not load the application: ${error.message}`);
  if (!data) return null;

  return {
    reference: data.reference as string,
    companyName: data.company_name as string,
    submittedAt: data.submitted_at as string,
  };
}

/**
 * Reads the public status page's data.
 *
 * Note the SELECT: four columns, none of them financial. Widening this list is the one
 * change that could leak borrower data, which is why it sits alone in a four-line function.
 */
export async function getApplicantStatus(accessToken: string): Promise<ApplicantStatusView | null> {
  const supabase = getSupabaseAdmin();

  const { data, error } = await supabase
    .from(TABLE)
    .select("reference, status, analyst_message, updated_at")
    .eq("access_token", accessToken)
    .maybeSingle();

  if (error) throw new Error(`Could not load the application: ${error.message}`);
  if (!data) return null;

  return {
    reference: data.reference as string,
    // A status the app does not recognise (added by hand in the Supabase table editor,
    // say) is shown as "submitted" rather than crashing the applicant's page.
    status: isApplicationStatus(data.status) ? data.status : DEFAULT_STATUS,
    analystMessage: (data.analyst_message as string | null) ?? null,
    statusUpdatedAt: data.updated_at as string,
  };
}

// =======================================================================================
// ANALYST QUERIES
// =======================================================================================

/**
 * A full application row as the analyst screens see it.
 *
 * Note what is NOT here: `access_token`. That column is the applicant's private key to
 * their own status page, and no analyst screen has any use for it. It is excluded from the
 * SELECT below rather than merely left unrendered, so it cannot reach a component, a props
 * payload or the browser even by accident.
 *
 * The money columns are typed `number | null` because PostgREST can return a Postgres
 * `numeric` as either a JSON number or a string depending on its magnitude, and because
 * rows created before the balance-sheet migration have NULL in the two newest columns.
 * Both are handled by `toNumber` below rather than being assumed away.
 */
export interface ApplicationRecord {
  id: string;
  reference: string;
  status: ApplicationStatus;
  analystMessage: string | null;
  submittedAt: string;
  updatedAt: string;

  // Company
  companyName: string;
  legalForm: string;
  registrationNumber: string | null;
  industry: string;
  country: string;
  yearFounded: number;
  employees: number;
  contactName: string;
  contactEmail: string;
  contactPhone: string | null;

  // Loan request
  loanAmountEur: number | null;
  loanTermMonths: number;
  loanPurpose: string;
  purposeDescription: string;

  // Financials. `totalLiabilitiesEur` and `equityEur` are null for rows submitted before
  // those fields existed; the analyst screens treat such a row as unscoreable.
  fiscalYear: number;
  revenueEur: number | null;
  revenuePriorYearEur: number | null;
  ebitdaEur: number | null;
  netIncomeEur: number | null;
  interestExpenseEur: number | null;
  existingDebtEur: number | null;
  totalAssetsEur: number | null;
  currentAssetsEur: number | null;
  /**
   * Null on any row submitted before cash was collected. That is NOT a gap that stops an
   * application being scored: the scorecard never uses cash, so an older row still produces
   * a full assessment - only the "cash exceeds current assets" check goes unrun.
   */
  cashEur: number | null;
  currentLiabilitiesEur: number | null;
  totalLiabilitiesEur: number | null;
  equityEur: number | null;
}

/**
 * Every column an analyst screen may read - and deliberately not `access_token`.
 *
 * Written out in full rather than as `*`, for the same reason the applicant queries are:
 * a SELECT that names its columns cannot start returning a new one just because somebody
 * added it to the table.
 */
const ANALYST_COLUMNS = [
  "id",
  "reference",
  "status",
  "analyst_message",
  "submitted_at",
  "updated_at",
  "company_name",
  "legal_form",
  "registration_number",
  "industry",
  "country",
  "year_founded",
  "employees",
  "contact_name",
  "contact_email",
  "contact_phone",
  "loan_amount_eur",
  "loan_term_months",
  "loan_purpose",
  "purpose_description",
  "fiscal_year",
  "revenue_eur",
  "revenue_prior_year_eur",
  "ebitda_eur",
  "net_income_eur",
  "interest_expense_eur",
  "existing_debt_eur",
  "total_assets_eur",
  "current_assets_eur",
  "cash_eur",
  "current_liabilities_eur",
  "total_liabilities_eur",
  "equity_eur",
].join(", ");

/**
 * Coerces a Postgres `numeric` into a JavaScript number.
 *
 * PostgREST may hand back a numeric as a JSON number or as a string. Parsing defensively
 * here means the rest of the app never has to care, and a value that will not parse becomes
 * null - which the analyst screens surface as "incomplete" - rather than a NaN that would
 * travel silently into the credit engine.
 */
function toNumber(value: unknown): number | null {
  if (typeof value === "number") return Number.isFinite(value) ? value : null;
  if (typeof value === "string" && value.trim() !== "") {
    const parsed = Number(value);
    return Number.isFinite(parsed) ? parsed : null;
  }
  return null;
}

function toRecord(row: Record<string, unknown>): ApplicationRecord {
  return {
    id: row.id as string,
    reference: row.reference as string,
    status: isApplicationStatus(row.status) ? row.status : DEFAULT_STATUS,
    analystMessage: (row.analyst_message as string | null) ?? null,
    submittedAt: row.submitted_at as string,
    updatedAt: row.updated_at as string,

    companyName: row.company_name as string,
    legalForm: row.legal_form as string,
    registrationNumber: (row.registration_number as string | null) ?? null,
    industry: row.industry as string,
    country: row.country as string,
    yearFounded: toNumber(row.year_founded) ?? 0,
    employees: toNumber(row.employees) ?? 0,
    contactName: row.contact_name as string,
    contactEmail: row.contact_email as string,
    contactPhone: (row.contact_phone as string | null) ?? null,

    loanAmountEur: toNumber(row.loan_amount_eur),
    loanTermMonths: toNumber(row.loan_term_months) ?? 0,
    loanPurpose: row.loan_purpose as string,
    purposeDescription: row.purpose_description as string,

    fiscalYear: toNumber(row.fiscal_year) ?? 0,
    revenueEur: toNumber(row.revenue_eur),
    revenuePriorYearEur: toNumber(row.revenue_prior_year_eur),
    ebitdaEur: toNumber(row.ebitda_eur),
    netIncomeEur: toNumber(row.net_income_eur),
    interestExpenseEur: toNumber(row.interest_expense_eur),
    existingDebtEur: toNumber(row.existing_debt_eur),
    totalAssetsEur: toNumber(row.total_assets_eur),
    currentAssetsEur: toNumber(row.current_assets_eur),
    cashEur: toNumber(row.cash_eur),
    currentLiabilitiesEur: toNumber(row.current_liabilities_eur),
    totalLiabilitiesEur: toNumber(row.total_liabilities_eur),
    equityEur: toNumber(row.equity_eur),
  };
}

/** Every application, newest first. Used by the analyst dashboard. */
export async function listApplicationsForAnalyst(): Promise<ApplicationRecord[]> {
  const supabase = getSupabaseAdmin();

  const { data, error } = await supabase
    .from(TABLE)
    .select(ANALYST_COLUMNS)
    .order("submitted_at", { ascending: false });

  if (error) throw new Error(`Could not load applications: ${error.message}`);
  // supabase-js cannot infer a row type from a runtime column string, so the cast goes
  // through `unknown`. toRecord validates and coerces every field it reads.
  return (data ?? []).map((row) => toRecord(row as unknown as Record<string, unknown>));
}

/**
 * One application by its internal id.
 *
 * The analyst route is keyed on `id`, the table's own primary key, NOT on `access_token`.
 * Those are two different identifiers with two different jobs: the token is a capability
 * that opens the applicant's status page for anyone holding the link, while the id is an
 * internal reference that grants nothing on its own. Routing the analyst screens on the
 * token would have put a working applicant-facing key into every analyst URL, browser
 * history and screen-share.
 */
export async function getApplicationForAnalyst(id: string): Promise<ApplicationRecord | null> {
  const supabase = getSupabaseAdmin();

  const { data, error } = await supabase.from(TABLE).select(ANALYST_COLUMNS).eq("id", id).maybeSingle();

  if (error) throw new Error(`Could not load the application: ${error.message}`);
  return data ? toRecord(data as unknown as Record<string, unknown>) : null;
}
