import "server-only";
import { getSupabaseAdmin } from "@/lib/supabase/server";
import { generateReference } from "./reference";
import { DEFAULT_STATUS, isApplicationStatus, type ApplicationStatus } from "./status";
import type { ApplicationInput } from "./schema";

/**
 * REPOSITORY: the only file in the app that knows the shape of the `applications` table.
 *
 * Everything else works with the typed objects below. If a column is renamed, this file
 * changes and nothing else does. It also means the two public pages cannot accidentally
 * read a column they should not: each query lists its columns explicitly, and the applicant
 * views do not name a single financial one.
 *
 * Column names are snake_case because that is Postgres convention; the app uses camelCase.
 * The mapping happens here, once.
 */

const TABLE = "applications";

/** What the caller gets back after a successful submission. */
export interface SubmittedApplication {
  reference: string;
  accessToken: string;
}

/**
 * What the CONFIRMATION page may show: the applicant is looking at this seconds after
 * typing it, on their own device.
 */
export interface ConfirmationView {
  reference: string;
  companyName: string;
  submittedAt: string;
}

/**
 * What the PUBLIC STATUS page may show, and the reason this type is narrow.
 *
 * The status page is reached by a link with a random token and no password. Anyone holding
 * that link, including anyone it was forwarded to, sees exactly these four values. So the
 * borrower's financial figures, the contact details and (from Day 3) the score and risk
 * grade are not in this type, are not in the SELECT that fills it, and therefore never
 * leave the database. Privacy is enforced by the query, not by remembering not to render
 * something.
 */
export interface ApplicantStatusView {
  reference: string;
  status: ApplicationStatus;
  analystMessage: string | null;
  statusUpdatedAt: string;
}

/** Postgres error code for a UNIQUE constraint violation. */
const UNIQUE_VIOLATION = "23505";

/**
 * Stores a validated application and returns its reference and status-page token.
 *
 * The reference is generated in the app, so two submissions arriving in the same
 * millisecond could in principle draw the same code. The database's UNIQUE constraint
 * catches that, and we simply try again with a new code. Three attempts is plenty: with a
 * 729-million-wide code space, a second collision is not a scenario worth engineering for.
 */
export async function insertApplication(input: ApplicationInput): Promise<SubmittedApplication> {
  const supabase = getSupabaseAdmin();

  for (let attempt = 1; attempt <= 3; attempt += 1) {
    const reference = generateReference();

    const { data, error } = await supabase
      .from(TABLE)
      .insert({
        reference,
        status: DEFAULT_STATUS,

        // Step 1: company information
        company_name: input.companyName,
        legal_form: input.legalForm,
        registration_number: input.registrationNumber,
        industry: input.industry,
        country: input.country,
        year_founded: input.yearFounded,
        employees: input.employees,
        contact_name: input.contactName,
        contact_email: input.contactEmail,
        contact_phone: input.contactPhone,

        // Step 2: loan request
        loan_amount_eur: input.loanAmountEur,
        loan_term_months: input.loanTermMonths,
        loan_purpose: input.loanPurpose,
        purpose_description: input.purposeDescription,

        // Step 3: financial information
        fiscal_year: input.fiscalYear,
        revenue_eur: input.revenueEur,
        revenue_prior_year_eur: input.revenuePriorYearEur,
        ebitda_eur: input.ebitdaEur,
        net_income_eur: input.netIncomeEur,
        interest_expense_eur: input.interestExpenseEur,
        existing_debt_eur: input.existingDebtEur,
        total_assets_eur: input.totalAssetsEur,
        current_assets_eur: input.currentAssetsEur,
        current_liabilities_eur: input.currentLiabilitiesEur,
        total_liabilities_eur: input.totalLiabilitiesEur,
        equity_eur: input.equityEur,
      })
      // access_token is generated by Postgres (gen_random_uuid), so we read it back
      // rather than inventing it here.
      .select("reference, access_token")
      .single();

    if (!error) {
      return { reference: data.reference as string, accessToken: data.access_token as string };
    }

    const isReferenceCollision = error.code === UNIQUE_VIOLATION && error.message.includes("reference");
    if (!isReferenceCollision || attempt === 3) {
      throw new Error(`Could not save the application: ${error.message}`);
    }
  }

  // Unreachable: the loop either returns or throws.
  throw new Error("Could not save the application.");
}

/** Reads the confirmation page's data. Returns null when the token matches nothing. */
export async function getConfirmation(accessToken: string): Promise<ConfirmationView | null> {
  const supabase = getSupabaseAdmin();

  const { data, error } = await supabase
    .from(TABLE)
    .select("reference, company_name, submitted_at")
    .eq("access_token", accessToken)
    .maybeSingle();

  if (error) throw new Error(`Could not load the application: ${error.message}`);
  if (!data) return null;

  return {
    reference: data.reference as string,
    companyName: data.company_name as string,
    submittedAt: data.submitted_at as string,
  };
}

/**
 * Reads the public status page's data.
 *
 * Note the SELECT: four columns, none of them financial. Widening this list is the one
 * change that could leak borrower data, which is why it sits alone in a four-line function.
 */
export async function getApplicantStatus(accessToken: string): Promise<ApplicantStatusView | null> {
  const supabase = getSupabaseAdmin();

  const { data, error } = await supabase
    .from(TABLE)
    .select("reference, status, analyst_message, updated_at")
    .eq("access_token", accessToken)
    .maybeSingle();

  if (error) throw new Error(`Could not load the application: ${error.message}`);
  if (!data) return null;

  return {
    reference: data.reference as string,
    // A status the app does not recognise (added by hand in the Supabase table editor,
    // say) is shown as "submitted" rather than crashing the applicant's page.
    status: isApplicationStatus(data.status) ? data.status : DEFAULT_STATUS,
    analystMessage: (data.analyst_message as string | null) ?? null,
    statusUpdatedAt: data.updated_at as string,
  };
}
